### ISSUE TITLE
поправить  верстку в ФФ

### ISSUE THREAD

**Issue by Markus3295** [codex-team/codex.editor#11]

**Comment by neSpecc** [comment]
а в чем баг?

**Comment by Markus3295** [comment]
криво выглядит добавление пустых параграфов


>Среда, 16 декабря 2015, 6:01 -08:00 от "Peter S." <notifications@github.com>:
>
>а в чем баг?
>—
>Reply to this email directly or  view it on GitHub .


------------------
С уважением,
Марк Дерманов
моб: +7 (921) 769-56-55
