### ISSUE TITLE
отображение кнопок добавления нового узла

### ISSUE THREAD

**Issue by Markus3295** [codex-team/codex.editor#12]
сделать отображение только одного плюса - у активного узла, а так же по ховеру на любом из узлов

**Comment by neSpecc** [comment]
у активного можно скрывать плюс. А при нажатии на TAB он появляется и превращается в крестик

**Comment by eliseealex** [comment]
Ни на ком не висит, перенёс в следующий майлстоун

**Comment by Markus3295** [comment]
так это вроде закрытая задача?
кнопки (кнопка плюс) уже отображаются по ховеру.
или тут что-то другое?


>Вторник, 22 декабря 2015, 10:43 -08:00 от Eliseev Alexandr <notifications@github.com>:
>
>Ни на ком не висит, перенёс в следующий майлстоун
>—
>Reply to this email directly or  view it on GitHub .


------------------
С уважением,
Марк Дерманов
моб: +7 (921) 769-56-55
