### ISSUE TITLE
Поведение тулбара

### ISSUE THREAD

**Issue by khaydarov** [codex-team/codex.editor#249]
- [x] Показывать кнопку плюс когда блок не имеет текстового контента. 

- [x] При нажатии на плюс открывать toolbox

- [x] Когда toobar открыт, нажатие на TAB листает элементы Toolbox-a, а нажатие на ENTER вставляет выбранный блок. Shift+Tab листает назад (issue #302)

**Comment by talyguryn** [comment]
closed in #330
