### ISSUE TITLE
Is there any example of plugin with uploading a file to the server?

### ISSUE THREAD

**Issue by zabavnikov** [codex-team/codex.editor#475]
Hello!

Also would like to know if there any events dispatched on block? Something like onBeforeDelete, onDelete.
Can I cancel block deletion if some condition wasn't met?

Thanks. 🙂

**Comment by gohabereg** [comment]
Здравствуйте!

Пример плагина с загрузкой на сервер будет. Следите за обновлением репозиториев в организации https://github.com/codex-editor/, в ближайшее время там появится плагин Image.

События есть в плане, будем добавлять постепенно. Сейчас класс плагина может реализовать метод appendCallback, который вызывается сразу после вставки блока.

P.S. Мы ориентируемся не только на русско-язычную аудиторию, поэтому ваш вопрос и ответ к нему будет переведен на английский

**Comment by gohabereg** [comment]
Hi there!
Image tool is ready and available here https://github.com/codex-editor/image
