### ISSUE TITLE
Запуск редактора для уже готовой статьи

### ISSUE THREAD

**Issue by eliseealex** [codex-team/codex.editor#5]
Нужно добавить возможность создавать редактор для уже готового текста, то есть на вход поступает объект в специальном формате, а на выходе будет статья, которая выглядит в редакторе так же, как и на сайте.

**Comment by Markus3295** [comment]
> на вход поступает объект в специальном формате

так было бы даже проще. 
но если хранить объект, как промежуточный вариант между редактированием статьи и ее отображением в публичке - то соответственно в шаблоне статьи надо будет не просто вывести статью "как есть", как это делается обычно, а обработать объект и на основании его параметров уже сгенерировать разметку.

а это потребует снабдить редактор еще серверным скриптом по генерации разметки, что усложняет процесс интеграции.

поэтому сохраненная статья будет просто помещена в textarea "как есть". Потом подключается редактор, добавляет нужные вспомогательные блоки (плюсы и тд), в зависимости от типа узла.

**Comment by eliseealex** [comment]
В этой задаче нужно интегрировать как пример редактор в Codex.
