### ISSUE TITLE
Вынести санитайз в метод API

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.editor#56]
Вынести 

``` javascript
block.addEventListener('paste', function (event) {
     cEditor.callback.blockPaste(event, block);
}, false);
```

в метод `activateSatizeOnPase` , который будет вешать разработчик плагина при создании contenteditable элемента

**Comment by khaydarov** [comment]
При вставке верстки санитайз срабатывает нормально, но каретка ведет себя не понятно (то в начале, то вообще пропадает)
При вставке верстки 1 раз все хорошо, а второй раз в этот же блок вставляется верстка
