### ISSUE TITLE
Instagram & Twitter

### ISSUE THREAD

**Issue by Butonix** [codex-team/codex.editor#610]
Why is it not possible to embed twitter instagram posts?

**Comment by gohabereg** [comment]
Hi there!

As you might know, Editor use Tools (or plugins) to work with different types of content. At the moment [Embed Tool](/codex-editor/embed) works only for services which use iframe for embedded content.
 
Twitter and Instagram use their own widgets that require loading external script to the page. So to embed twitter or instagram posts you need some other plugin. 

We are focused on the Editor's core development at the moment and do not have extra time for new plugins, so you have two options: wait until we have time to create a tool for twitter and instagram or create it yourself. Please feel free to ask any questions!

**Comment by kornarakis** [comment]
@gohabereg You can add instragram like that
```
instagram: {
    regex: /https?:\/\/www\.instagram\.com\/p\/([^\/\?\&]+)\/?/,
    embedUrl: 'https://www.instagram.com/p/<%= remote_id %>/embed',
    html: '<iframe width="400" height="505" style="margin: 0 auto;" frameborder="0" scrolling="no" allowtransparency="true"></iframe>',
    height: 505,
    width: 400
},
```

**Comment by Aror** [comment]
@kornarakis That is not a good solution. Relying on 3rd party service is opening up to potential security vulnerabilities.
