### ISSUE TITLE
Добавить заголовки в редактор

### ISSUE THREAD

**Issue by eliseealex** [codex-team/codex.editor#7]
Добавить возможность работы с заголовками в редакторе.

При открытии редактора можно ставить курсор на большой заголовок (в случае статей — это название статьи). 
А после того, как закончена работа с заголовком по Enter переходить в первый текстовый блок.

`#` это заголовок H1, `##` это заголовок H2, ну или H2 и H3 соответственно.

**Comment by neSpecc** [comment]
мне кажется, заголовок статьи будет идти отдельным полем, вне редактора. Редактор верстает именно тело статьи. Поэтому в самом редакторе я бы сделал оформление H2-H6 (или хотябы трех)
