### ISSUE TITLE
Link tool

### ISSUE THREAD

**Issue by khaydarov** [codex-team/codex.editor#73]
Ошибка когда в инпут поле вставляется ссылка без 'path'

**Comment by n0str** [comment]
Это ссылки вида: www.google.com ? Они же вроде всегда загружались. Тогда фикс вроде такого:
`'linkText'  => $url_params["host"] . isset($url_params["path"])?$url_params["path"]:"",`

**Comment by khaydarov** [comment]
Хорошо, сегодня исправлю
