### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by khaydarov** [codex-team/codex.editor#97]

**Comment by talyguryn** [comment]
при инициализации редактора с содержимым не появляется сохраненная отметка cover

**Comment by talyguryn** [comment]
tab в тулбара после списка идет дальше по блокам статьи, не перепрыгивая на пункт "цитата"

**Comment by gohabereg** [comment]
не прикрепляется фото к цитате

**Comment by khaydarov** [comment]
Санитайз: 
1) При вставке верстки санитайз срабатывает нормально, но каретка ведет себя не понятно (то в начале, то вообще пропадает)
2) При вставке верстки 1 раз все хорошо, а второй раз в этот же блок вставляется верстка

**Comment by talyguryn** [comment]
полная беда со вставкой текста в пункт списка

**Comment by khaydarov** [comment]
блок удаляется если каретка в начале текста, но при этом текст существует

**Comment by gohabereg** [comment]
Настройки цитаты не работают

**Comment by gohabereg** [comment]
У списка тоже настройки не работают

**Comment by talyguryn** [comment]
стоят два блока "параграф" подряд. если нажимаешь backspace в начале второго блока, то содержимое второго блока переходит в первый.
косяк в том, что каретка улетает в конец всего суммированного текста в первом блоке
**должна оставаться за последним символом первого блока.**

**Comment by khaydarov** [comment]
По поводу цитат, мы его сами убрали.

**Comment by gohabereg** [comment]
Тогда надо варианты убрать

Не пойму, насколько баг:
на ifmo.su
![list1](https://cloud.githubusercontent.com/assets/23050529/21295388/1927a4da-c565-11e6-8019-1ce3d0844d75.png)
на сервере Виталика:
![list2](https://cloud.githubusercontent.com/assets/23050529/21295390/277dfc28-c565-11e6-8ec0-a25455f5947d.png)

**Comment by talyguryn** [comment]
вставляешь текст в первый блок. энтер. вставляешь текст во второй блок. из второго блока ты никак не можешь подняться в первый стрелками

**Comment by talyguryn** [comment]
@gohabereg у меня со стилями проблемы, вероятно

**Comment by khaydarov** [comment]
<img width="911" alt="2016-12-18 21 04 28" src="https://cloud.githubusercontent.com/assets/6507765/21295412/c03e8fd6-c565-11e6-8609-580fec9c2738.png">

**Comment by talyguryn** [comment]
к вопросу странного поведения модуля paste. каретка улетает в начало, а перед текстом появляется символ. не знаю уж, пробел это или какой-то специальный символ, но сам факт его появления меня огорчает.
виден в блоке code. не виден в любом другом блоке
<img width="694" alt="screen shot 2016-12-18 at 21 06 28" src="https://cloud.githubusercontent.com/assets/15259299/21295434/10206e16-c566-11e6-9519-bb8b27eba10a.png">

**Comment by talyguryn** [comment]
при попытке удалить лишний символ в ссылке удаляется весь блок link

**Comment by talyguryn** [comment]
ну и не работает link в сафари 😡
